### ISSUE TITLE
Review and merge contribution banner

### ISSUE THREAD

**Issue by serra** [XSCALE-Alliance/wiki#3]
How to afford editing?
Help on editing
Understand what is going to happen
Hide global saves

Proposed changes to edit tiddler:

* [x] hide save + delete buttons in edit tiddler
* [x] update text to say you can use this area to format the text

Proposed changes to global buttons:
* [x] remove save button

Update _Editing the Wiki_
* [ ] ~~update _Editing the Wiki_~~ replaced by #5

Unresolved:
* how do we allow people to add new pages? It's more complex since it requires adding headers. Can we ignore this for now?

**Comment by serra** [comment]
@jamesgorman2 upgraded to an issue to allow for discussion here.

I think we can ignore the add new page functionality.

If people want to that, we can quickly do that for them at this stage.
First let's get them on Github once 😄

**Comment by jamesgorman2** [comment]
I've put in #4 so we can look at how it works not _before_ updating the _Editing the Wiki_ page.

**Comment by jamesgorman2** [comment]
> I think we can ignore the add new page functionality.

I'm happy with this

**Comment by jamesgorman2** [comment]
With #1 playing up, do we want to get this over to Pete as is to check?

**Comment by serra** [comment]
I think we can stick to the order in the todo column.

https://github.com/XSCALE-Alliance/wiki/projects/1

Once #1 is done (it needs a little love) then we should check with @zefram-cochrane , a.k.a. the man who invented warp drive.
