### ISSUE TITLE
Switch to Markdown for Tiddler format

### ISSUE THREAD

**Issue by serra** [XSCALE-Alliance/wiki#7]
There's a plugin for this: https://tiddlywiki.com/plugins/tiddlywiki/markdown/

Pros:

 * Accessible to more users
 * Integration in the github ui
 * More portable if we want to ... 
   * move to another wiki engine/solution
   * export parts of the wiki to the xscale guide

Cons:

 * Not all TW's functionality is supported in Markdown? (although this can be seen as a pro as well)
 * We have to migrate the entire wiki to Markdown as a hybrid markup wiki might be confusing to users and will degrade portability

**Comment by zefram-cochrane** [comment]
Hi Marijn,

* What functionality isn’t supported?
* Should we move this discussion to slack so the rest of the coaches can contribute to it?

Cheers,
Pete

**Comment by serra** [comment]
We probably should continue discussing this after we have acquired and activated some coaches to our wiki ecosystem.
